config/routes.rb
Brick::Application.routes.draw do
  resources :sessions
  resources :users  
  resources :surveys

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'static_pages#home'

  match '/home' => 'static_pages#home'
  match '/survey' => 'static_pages#survey'
  match '/results' => 'static_pages#results'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :survey_id, :answers_attributes
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, :allow_destroy => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :name, :questions_attributes
  has_many :questions
  accepts_nested_attributes_for :questions, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  attr_accessible :email, :password, :password_digest, :password_confirmation

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def authorize
	  redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

	def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to root_url, notice: "Logged in!"
	  else
	    flash.now.alert = "Email or password is invalid"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "Logged out!"
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_shim.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content=""> 
    <title>Brick</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="container">
      <div id="user_header">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/_comments.html.erb
<!-- begin htmlcommentbox.com -->
 <div id="HCB_comment_box"><a href="http://www.htmlcommentbox.com">HTML Comment Box</a> is loading comments...</div>
 <link rel="stylesheet" type="text/css" href="//www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
 <script type="text/javascript" language="javascript" id="hcb"> /*<!--*/ if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=(""+window.location || hcb_user.PAGE), h="//www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+escape(l).replace("+","%2B")+"&mod=%241%24wq1rdBcg%24zKq9.ym3mhkXn0KwFx5bl1"+"&opts=16862&num=10");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})(); /*-->*/ </script>
<!-- end htmlcommentbox.com -->

app/views/static_pages/home.html.erb
<body>
<div class="masthead">
  <div class="row-fluid">
    <div class="heading-container span8">
      <h1>Brick</h1>
      <h3>A platform for friends to help develop your startup</h3>
    </div>
    <div class="span4">
      <div class="balloon-container">
        <div class="row-fluid">
          <div class="span10 offset1">
            <div class="balloon-size">
              <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSM8H_L8TiVLuc7XBwrJJm7Cmsf2J0dbUfsBbPUmHqx4rOGQapdVQ"/>
              <div class="button-holder"> 
                <a class="btn button-feedback" href="/surveys/1">Give Feedback</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 	
  </div>
</div>
<div class="diagram-container">
  <div class="row-fluid">
    <div class="span4">
      <div class="img-resize">
        <img src="http://openclipart.org/image/250px/svg_to_png/48763/3-plait_border_circle.png" />
      </div>
      <p>You have an idea for a startup, you have put together a prototype and now you want some early feedback.</p>
    </div>
    <div class="span4">
      <div class="img-resize">
        <img src="http://openclipart.org/image/250px/svg_to_png/48763/3-plait_border_circle.png" />
      </div>
      <p>So you tap into your network of friends and peers.</p>
    </div>
    <div class="span4">
      <div class="img-resize">
        <img src="http://openclipart.org/image/250px/svg_to_png/48763/3-plait_border_circle.png" />
      </div>
      <p>Brick provides the platform for them to share their feedback and engage with your idea in a meaningful way.</p>
    </div>  
  </div>  
</div>
</body>

app/views/static_pages/results.html.erb
<div id="results-page-container">
  <div class="row-fluid">
    <div class="span6" id="results-section-container">
      <div id="survey-results-container">
        <h1 class="results-header">Survey Results</h1>
        <div class="survey-question" id="survey-question-lead">
          1) How do you currently solicit feedback from friends on your startup?
        </div>
        <div class="survey-result-answer">
          <img src="assets/piechart1.png" width="450" height="200">
        </div>
        <div class="survey-question">
          2) Would you use Brick to generate feedback from your friends?
        </div>
        <div class="survey-result-answer">
          <img src="assets/barchart1.png" width="450" height="100">
        </div>
        <div class="survey-question">
          3) How much would you pay to use Brick?
        </div>
        <div class="survey-result-answer">
          <img src="assets/piechart2.png" width="450" height="200">
        </div>
      </div>
    </div>
    <div class="span6" id="results-section-container">
      <h1 class="results-header">Comment Board</h1>
      <%= render "static_pages/comments" %>
    </div>
  </div>
</div>

app/views/static_pages/survey.html.erb
<div class="row-fluid">
  <div class="span6 offset3">
    <div id="survey-container">
      <div class="survey-question" id="survey-question-lead">
        1) How do you currently solicit feedback from friends on your startup?
      </div>
      <div class="answer-options">
        Talk to them about the idea over the phone
      </div>
      <div class="answer-options">
        I email a link to them and ask for feedback
      </div>
      <div class="answer-options">
        I meet with them
      </div>
      <div class="answer-options">
        I ask for comments on Facebook
      </div>
      <div class="answer-options">
        Other
      </div>
      <div class="survey-question">
        2) Would you use Brick to generate feedback from your friends?
      </div>
      <div class="row" id="answer-yn">
        <div class="answer-options-yn">
          Yes
        </div>
        <div class="answer-options-yn">
          No
        </div>
      </div>
      <div class="survey-question">
        3) How much would you pay to use Brick?
      </div>
      <div class="row" id="answer-yn">
        <div class="answer-options-yn">
          $0
        </div>
        <div class="answer-options-yn">
          $5
        </div>
        <div class="answer-options-yn">
          $10
        </div>
        <div class="answer-options-yn">
          $20
        </div>
        <div class="answer-options-yn">
          >$20
        </div>
      </div>
      <div class="button-holder">
        <div class="btn btn-large btn-submit">
          Submit
        </div>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %> 
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', :class => "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<div class="survey-builder-container">
  <%= form_for(@survey) do |f| %>
    <% if @survey.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

        <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    
    <%= f.fields_for :questions do |builder| %>
      <%= render 'question_fields', :f => builder %>
    <% end %>
    <%= link_to_add_fields "Add Question", f, :questions %>
    
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<div class="survey-builder-container">
  <table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @surveys.each do |survey| %>
    <tr>
      <td><%= survey.name %></td>
      <td><%= link_to 'Show', survey %></td>
      <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
      <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Survey', new_survey_path %>
</div>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<!--set for light background 
<div class="color-set-optional"> 
-->
<div class="survey-special-container">
  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="survey-builder-container">
        <h1 id="survey-header">Brick Survey</h1>
        <div class="survey-intro-container">
          <a href="/home">
            <img class="screenshot-img" src="/assets/brick_screenshot3.png">
          </a>
        </div>
        <div class="survey-qa-container">
          <ol class="questions">
          <% @survey.questions.each do |question| %>
            <li>
              <%= question.content %>
              <ol class="answers">
                <% question.answers.each do |answer| %>
                  <li><%= answer.content %></li>
                <% end %>
              </ol>
            </li>
          <% end %>
          </ol>
        </div>
      </div>
    </div>

  
  </div>
  <%= link_to 'Edit', edit_survey_path(@survey) %> |
  <%= link_to 'Back to Surveys', surveys_path %>
</div>

app/views/surveys/show1.html.erb
<div class="row-fluid">
  <div class="span8 offset2">
    <div class="survey-builder-container">
      <div class="survey-intro-container">
        <div class="row-fluid">
          <div class="span8">
            <a class="startup-name" href="/home"><%= @survey.name %></a>
            <div class="startup-subtitle">
              A platform for friends to help develop your startup
            </div>
          </div>
          <div class="span4 site-link-container">
            <a class="site-link" href="/home">Visit Brick</a>
          </div>
        </div>
      </div>
      <div class="survey-qa-container">
        <ol class="questions">
        <% @survey.questions.each do |question| %>
          <li>
            <%= question.content %>
            <ol class="answers">
              <% question.answers.each do |answer| %>
                <li><%= answer.content %></li>
              <% end %>
            </ol>
          </li>
        <% end %>
        </ol>


        <%= link_to 'Edit', edit_survey_path(@survey) %> |
        <%= link_to 'Back to Surveys', surveys_path %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/show_1.html.erb
<div class="row-fluid">
  <div class="span8 offset2">
    <div class="survey-builder-container">
      <div class="survey-intro-container">
        <div class="row-fluid">
          <div class="span8">
            <a class="startup-name" href="/home"><%= @survey.name %></a>
            <div class="startup-subtitle">
              A platform for friends to help develop your startup
            </div>
          </div>
          <div class="span4 site-link-container">
            <a class="site-link" href="/home">Visit Brick</a>
          </div>
        </div>
      </div>
      <div class="survey-qa-container">
        <ol class="questions">
        <% @survey.questions.each do |question| %>
          <li>
            <%= question.content %>
            <ol class="answers">
              <% question.answers.each do |answer| %>
                <li><%= answer.content %></li>
              <% end %>
            </ol>
          </li>
        <% end %>
        </ol>


        <%= link_to 'Edit', edit_survey_path(@survey) %> |
        <%= link_to 'Back to Surveys', surveys_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>